#!/bin/bash 
#SBATCH -D /clusterfs/vector/scratch/makman/Hubnerdata/newFiltering/
#SBATCH -J vcfFilter
#SBATCH --partition=vector
#SBATCH --qos=vector_batch
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=18000
#SBATCH --time=48:00:00
#SBATCH -o /clusterfs/vector/scratch/makman/ancestry/outs/ancestry_dataStructure.out
#SBATCH -e /clusterfs/vector/scratch/makman/ancestry/outs/ancestry_dataStructure.err
#SBATCH --mail-user=makman@berkeley.edu
#SBATCH --mail-type=All
#SBATCH --array=1-17
module load python
# gunzip *_ordered.vcf.gz
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr01_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr01_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr02_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr02_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr03_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr03_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr04_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr04_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr05_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr05_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr06_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr06_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr07_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr07_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr08_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr08_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr09_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr09_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr10_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr10_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr11_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr11_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr12_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr12_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr13_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr13_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr14_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr14_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr15_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr15_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr16_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr16_ancestry_dataStructure.txt
python /clusterfs/vector/scratch/makman/ancestry/ancestry_informative_from_vcf_dataStructure.py HanXRQChr17_complete_ordered_norm_maf_filt_indel_in_ordered.vcf HanXRQChr17_ancestry_dataStructure.txt
