#!/bin/bash 
#SBATCH -D /global/scratch/makman/Sunflower_paleomix/analyses/
#SBATCH -J angsd1
#SBATCH --account=fc_blackman
#SBATCH --partition=savio2
#SBATCH --qos=savio_normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --time=72:00:00
#SBATCH -o /global/home/users/makman/paloemix_outs/angsd_filterbams.out
#SBATCH -e /global/home/users/makman/paloemix_outs/angsd_filterbams.err
#SBATCH --mail-user=makman@berkeley.edu
#SBATCH --mail-type=All

module load samtools
 -o 
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Anzac_Pueblo_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Anzac_Pueblo_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Ari_Mand_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Ari_Mand_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Ari_broa_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Ari_broa_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Arikara_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Arikara_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA124_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA124_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA207_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA207_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA259_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA259_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA314_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA314_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA316_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA316_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA323_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA323_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA380_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA380_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA404_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA404_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA433_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA433_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA442_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA442_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA821_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA821_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/HA89_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/HA89_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Havasupai_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Havasupai_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Hidatsa1_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Hidatsa1_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Hopi_dye_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Hopi_dye_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Hopi_mapping_parent_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Hopi_mapping_parent_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Hopi_other_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Hopi_other_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Hopi_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Hopi_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Laguna_Pueblo_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Laguna_Pueblo_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Mandan1_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Mandan1_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Mandan2_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Mandan2_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/MexCult14_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/MexCult14_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/MexCult15_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/MexCult15_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/MexCult1_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/MexCult1_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/MexCult3_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/MexCult3_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/MexCult6_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/MexCult6_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/MexCult7_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/MexCult7_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/MexCult9_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/MexCult9_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Paiute_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Paiute_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Pueblo_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Pueblo_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA271_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA271_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA309_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA309_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA310_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA310_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA324_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA324_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA328_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA328_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA354_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA354_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA358_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA358_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA362_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA362_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA397_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA397_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA408_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA408_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA426_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA426_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/RHA857_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/RHA857_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/SF33_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/SF33_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Se137749_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Se137749_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Se_purp_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Se_purp_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Se_strip_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Se_strip_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Seneca_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Seneca_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/Zuni_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/Zuni_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann01-cwIA_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann01-cwIA_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann04-nwAR_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann04-nwAR_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann05-ccNM_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann05-ccNM_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann06-seWY_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann06-seWY_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann08-ceTN_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann08-ceTN_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann10-ccIL_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann10-ccIL_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann20-seAZ_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann20-seAZ_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann28-swSK_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann28-swSK_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann29-neSD_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann29-neSD_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann34-cwKS_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann34-cwKS_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann39-ncNE_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann39-ncNE_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/ann44-ccCA_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/ann44-ccCA_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annIA1W-1_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annIA1W-1_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annIA2W-17_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annIA2W-17_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annIA_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annIA_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annKS1W-27_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annKS1W-27_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annKS2W-35_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annKS2W-35_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annKS_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annKS_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annMB1W-40_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annMB1W-40_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annMO1W-39_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annMO1W-39_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annMex_A1516_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annMex_A1516_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annMex_A1517_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annMex_A1517_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annMex_A1572_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annMex_A1572_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annMex_A1574_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annMex_A1574_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annMex_Ann261_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annMex_Ann261_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annND1W-6_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annND1W-6_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annNM_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annNM_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annSD1W-35_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annSD1W-35_sorted_markdup_readGroup_filtered.bam
samtools view -b -L /global/home/users/makman/git/Helianthus/shells/aDNA/angsd/chr_file.txt /global/scratch/makman/GATK/sams/bams/annSD2W-18_sorted_markdup_readGroup.bam -o /global/scratch/makman/GATK/sams/bams/annSD2W-18_sorted_markdup_readGroup_filtered.bam
 -o 